#include "MLS800.h"

//read user input and map from the power of two to button number
uint8_t readInput()
{
	_inputInterrupted = false;
	//active input is LOW, inverting the uint8_ts
	uint16_t current = ~_display.read();

	uint8_t value = 1;

	//interrupt was generated by an input release
	if (current == LOW) return current;

	while (current != 1) {
		current = current >> 1;
		value++;
	}

	return value;
}

void applyLoopStates(uint8_t state)
{

	_loops.write(transformState(state) | (transformState(state >> 4) << 8));
	delay(7);
	//lay down the previous impulse
	_loops.write(0x0000);
	debugPrint("applied state : ");
	debugPrintlnBase(state, BIN);
}

uint8_t transformState(uint8_t state)
{
	uint8_t result = 0;
	for (uint8_t i = 0; i < 4; i++) {
		if ((state & (1 << i)) != 0) result += 1 << (2 * i + 1);
		else result += 1 << (2 * i);
	}

	return result;
}