#include "MLS800.h"

//read user input and map from the power of two to button number
byte readInput()
{
	input = false;
	//active input is LOW, inverting the bytes
	unsigned short current = ~_display.read();

	byte value = 1;

	//interrupt was generated by an input release
	if (current == LOW) return current;

	while (current != 1) {
		current = current >> 1;
		value++;
	}

	return value;
}

void applyLoopStates(byte state)
{
	_loops.write(state | ~state << 8);
	delay(7);
	//lay down the previous impulse
	_loops.write(0x0000);
	debugPrint("applied state : ");
	debugPrintlnBase(state, BIN);
}